#1712603 - Lê Quang Nam

<h1> BÀI TẬP 3 </h1>

Câu 1:

Ma trận chuyển của xích Markov $\{X_0,X_1,...\}$ có tập trạng thái $\{0,1,2\}$ là:

In [20]:
from fractions import Fraction as F
import numpy as np
P = np.matrix([
    [F(1,2),F(1,6),F(1,3)],
    [0,F(2,3),F(1,3)],
    [F(1,2),0,F(1,2)]
])
print(P)
X0 = [0.25,0.25,0.5]
print(X0)

[[Fraction(1, 2) Fraction(1, 6) Fraction(1, 3)]
 [0 Fraction(2, 3) Fraction(1, 3)]
 [Fraction(1, 2) 0 Fraction(1, 2)]]
[[0.25 0.25 0.5 ]]


Biết $P(X_0 = 0) = P(X_0 = 1)$ = $\frac{1}{4} , P(X_0 = 2) = \frac{1}{2} $

a. $$P(X_9 = 0 | X_1 = 2 , X_7 = 1,X_4 = 2)$$

= $$P(X_9 = 0 |  X_7 = 1)$$

In [10]:
from fractions import Fraction as F
import numpy as np
P_2 = P**2
print(P_2[1,0])

1/6


b. $$P(X_0 = 2 | X_1 = 1)$$

Dùng định lý Bayes ta có: 

$$P(X_0 = 2 | X_1 = 1) = \frac{P(X_0 = 2)P(X_1=1|X_0 = 2)}{P(X_1) = 1}$$

$$P(X_0 = 2 | X_1 = 1) = P_{1,2}$$

In [12]:
P[1,2]

Fraction(1, 3)

In [39]:
X0[0,2]

0.5

Phân phối của $X_1$ là $\alpha P$

In [27]:
X1 = X0 * P
print(X1)

[[0.375 0.20833333333333331 0.41666666666666663]]


In [38]:
X1[0,1]

0.20833333333333331

In [41]:
X0[0,2]*P[1,2]/X1[0,1]

0.8

Vậy $$P(X_0 = 2 | X_1 = 1) = 0.8 $$

c. $$P(X_1 = X_3 = 2)$$

Dùng công thức nhân ta được:
    $$P(X_1= 2,X_3 = 2) = P(X_1 = 2)P(X_3 = 2 | X_1 = 2)$$

Ta xét : $$P(X_3 = 2 | X_1 = 2) = P_{2,2}$$

In [94]:
P22 = P**2[2,2] =  0 

In [95]:
X1[0,2]

0.41666666666666663

Vậy $P(X_1 = X_3 = 2) = P22 * X1[0,2]$ = 0

d. $$E(X_3)$$

Ta có $X_3$ là biến ngẫu nhiên rời rạc nhận các giá trị $S = \{1,2,3\}$

Phân phối của $X_3 = \alpha P^2$

In [65]:
from fractions import Fraction as F
import numpy as np
P = np.matrix([
    [F(1,2),F(1,6),F(1,3)],
    [0,F(2,3),F(1,3)],
    [F(1,2),0,F(1,2)]
])
print(P)
X0 = [0.25,0.25,0.5]
print(X0)
X3 = X0 * P**3
print(X3)

[[Fraction(1, 2) Fraction(1, 6) Fraction(1, 3)]
 [0 Fraction(2, 3) Fraction(1, 3)]
 [Fraction(1, 2) 0 Fraction(1, 2)]]
[0.25, 0.25, 0.5]
[[0.3993055555555556 0.20023148148148148 0.40046296296296297]]


Kì vọng của $X_3$ là:
$$E(X_3) = \sum_{k \in S} kP(X_3 = k)$$

In [44]:
S = np.matrix([
    [1],
    [2],
    [3]
])
print(S)

[[1]
 [2]
 [3]]


In [66]:
E_X = X3*S
print(E_X)

[[2.0011574074074074]]


Câu 2:

Ta có $Y_n = 3X_n$ với $n = \{0,1,2,...\}$ 

=> $$Y_0 = X_0$$
   $$Y_1 = X_3$$
   $$Y_2 = X_6$$
   $$Y_3 = X_9$$
   $........$

Vì vậy ta thấy $P(Y_1|Y_0)$ = $P(X_3|X_0)$
Vì vậy Y là 1 xích Markov với ma trận chuyển là ma trận chuyển 3 bước của X 

Câu 3:

Xác suất để đổi bi giữa bi đỏ và bi đen là như nhau, suy ra:

Ta có $X_0 = [0.5,0.5] $

Bốc được 1 bi thì xác suất thay bi cùng màu là 0.7 và xác suất thay bi khác màu là 0.3. Ta có ma trận Cùng và Khác như sau:
Bi đầu tiên là bi đỏ và tập trạng thái $S = \{0,1\}$

In [69]:
import numpy as np
P = np.matrix([
    [0.7,0.3],
    [0.3,0.7]
])
X0 = [0.5,0.5]
print(P)
print(X0)

[[0.7 0.3]
 [0.3 0.7]]
[0.5, 0.5]


Tính $P(X_5 = 0) $

In [53]:
X0[0]

0.5

In [70]:
P_5 = P**5
print(P_5)

[[0.50512 0.49488]
 [0.49488 0.50512]]


$P(X_5 = 0)$ = $\alpha P^5 $

In [79]:
X_5 = X0*P**5
print(X_5)

[[0.5 0.5]]


Vậy xác suất ra bi màu đỏ ở lần bốc thứ 5 là xấp xỉ 0.5 ~ 0.50005(Theo như bấm tay)